### ISSUE TITLE
Make Custom Note Header Template setting allow multiple lines

### ISSUE THREAD

**Issue by shabegom** [renehernandez/obsidian-readwise#25]
I'd like to write my note headers as YAML frontmatter, but the text box in settings only allows a single line. Maybe it supports "\n"? Would be great if it was a `<textarea>` element instead of an `<input>` element.

Thanks for the plugin! It's working great!

**Comment by renehernandez** [comment]
The setting is for specifying the path to a note that will have the Template structure for the header, instead of the actual template content.

**Comment by renehernandez** [comment]
Defining the template directly on the Settings tab looks like a good option. I'll do some research about how other plugins approach providing template customizations

**Comment by shabegom** [comment]
Ahhh! I didn't know it was meant to be for a path to a note 🙈 . My Bad!

**Comment by renehernandez** [comment]
@shabegom I have improved the description in the Settings so that it mentions it is pointing to a path. That will show up in version 0.0.3.
