### ISSUE TITLE
Readwise Plugin not listed in Plugin option menu

### ISSUE THREAD

**Issue by brigittethecat** [renehernandez/obsidian-readwise#44]
I have installed and enabled the Readwise Community Plugin, but the Plugin is not listed in the Plugin Options menu. I can’t access the Readwise Community Plugin settings.

**Comment by renehernandez** [comment]
Which obsidian version are you using?

**Comment by brigittethecat** [comment]
I’m using the mobile app: 0.0.17 (4). I can’t access the plugin settings. I’ve tried to uninstall and install it again, but. It didn’t work.

**Comment by renehernandez** [comment]
> I’m using the mobile app: 0.0.17 (4). I can’t access the plugin settings. I’ve tried to uninstall and install it again, but. It didn’t work.

I think that is due to https://forum.obsidian.md/t/new-plugin-readwise/16006/13, in essence it is trying to attach to the status bar, which doesn't exist on Mobile.

I'll add a fix for it.
