### ISSUE TITLE
Ignore Highlight ID

### ISSUE THREAD

**Issue by vincentteoh** [renehernandez/obsidian-readwise#53]
Hi,

Is it possible to ignore the highlight ID? I don't want it to be included in my content.

I have tried the following code but it still adding the highlight ID at the end.

`{{ text }} {% if note -%} Note: {{ note }} {%- endif %}`

Thank you.

**Comment by renehernandez** [comment]
@vincentteoh It isn't possible. That's how the plugin tracks what has been written into the note. It will become specially relevant when we finally implement support to sync the whole library.

> I have tried the following code but it still adding the highlight ID at the end.

If the highlight is not present, the plugin adds it automatically

**Comment by vincentteoh** [comment]
> @vincentteoh It isn't possible. That's how the plugin tracks what has been written into the note. It will become specially relevant when we finally implement support to sync the whole library.
> 
> > I have tried the following code but it still adding the highlight ID at the end.
> 
> If the highlight is not present, the plugin adds it automatically

Noted and thank you for your reply.
